baseURL = "https://jefferdev.github.io/microsoft-cybersec/"
canonifyURLs = true
relativeURLs = false

title = "Microsoft Cybersecurity Blog"
defaultContentLanguage = "es"
enableEmoji = true
theme = ["PaperMod"]



[languages]
  [languages.es]
    languageName = "Español"
    languageCode = "es"
    weight = 1

[params.profileMode]
enabled = false


[params]
  author = "Jefferson Castiblanco"
  description = "Laboratorios reales de ciberseguridad en Microsoft 365"
  avatar = "/static/img/authors/jefferson.jpg"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = true

[[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 10

[[menu.main]]
  name = "Búsqueda"
  url = "search/"
  weight = 20

[[menu.main]]
  name = "Acerca"
  url = "about/"
  weight = 30


[outputs]
  home = ["HTML", "RSS", "JSON"]

